### PR TITLE
Add K8s example

### PR DESCRIPTION
**Pull request by Moser-ss**
This PR is to resolve issue #1 
It is using the kubectl apply because it was the more simplest way to define all the resources need to show the experience

### CODE REVIEW

**Comment by Moser-ss** [comment]
Hey @BretFisher,  do you think it will be nice to have an intro about the differences between Docker Heatlcheck and the readiness and liveness Probes in Kubernetes?

**Comment by BretFisher** [comment]
I'd say a separate PR that has links to reference docs and the differences is good. I wouldn't want this readme to become a article on HC though.

**Comment by BretFisher** [comment]
Hey are you looking for hacktoberfest credit? (if so I just need to opt-in and tag it)

**Comment by Moser-ss** [comment]
I update the branch with more info about Probes and links to documentation.
I made this PR because I like this image when I saw it in your course and I already used to test some rollback techniques in Kubernetes.
I think this is a way I could express how thankful I am for your work. 
So my intention was not the hacktoberfest credit, I even didn't notice the hacktoberfest if you didn't mention,

**Comment by Moser-ss** [comment]
@BretFisher should I change anything in this PR  or it is Ok to be merged?

**Comment by BretFisher** [comment]
Thanks for the PR @Moser-ss, sorry for the delay.

**Pull request merged**
